Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the database asn if there is a need of creating some aggregated tables that can help with:-

   1- Vendor selection for profitabilty
   2- Product Pricing Optimization

In [5]:
import pandas as pd
import _sqlite3

conn = _sqlite3.connect('inventory.db')

In [20]:
# checking tables present in the database
tables = pd.read_sql_query("Select name FROM sqlite_master Where TYPE = 'table'", conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [21]:
# To check no of record of any table
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of record:', pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of record: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of record: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of record: 484066

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of record: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of record: 432356

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of record: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [22]:
# To check one specific vendor detail - so selected VendorNumver = 4466 from purchases table
purchases = pd.read_sql("""select * from purchases where VendorNumber = 4466""",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,23_ARBINGTON_5215,23,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9491,2024-03-24,2024-03-31,2024-04-09,2024-05-08,9.41,6,56.46,1
308,75_BARNCOMBE_5255,75,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9491,2024-03-24,2024-03-31,2024-04-09,2024-05-08,9.35,6,56.10,1
309,60_IRRAGIN_5215,60,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9491,2024-03-24,2024-03-31,2024-04-09,2024-05-08,9.41,6,56.46,1
310,15_WANBORNE_5215,15,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9491,2024-03-24,2024-03-29,2024-04-09,2024-05-08,9.41,6,56.46,1
311,8_ALNERWICK_5215,8,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,9491,2024-03-24,2024-03-31,2024-04-09,2024-05-08,9.41,5,47.05,1

In [23]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
5215  9.41               1021   9607.61
5255  9.35               1096  10247.60

In [24]:
# To check one specific vendor detail - so selected VendorNumver = 4466 from purchase_prices table
purchase_prices = pd.read_sql("""select * from purchase_prices where VendorNumber = 4466""",conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [25]:
    # To check one specific vendor detail - so selected VendorNumver = 4466 from vendor_invoice table
vendor_invoice = pd.read_sql("""select * from vendor_invoice where VendorNumber = 4466""",conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [26]:
vendor_invoice['PONumber'].nunique()

55

In [27]:
vendor_invoice['PONumber'].unique()

array([ 8137,  8207,  8307,  8469,  8532,  8604,  8793,  8892,  8995,
        9033,  9180,  9244,  9371,  9491,  9583,  9639,  9800,  9886,
        9999, 10095, 10169, 10257, 10346, 10445, 10600, 10695, 10777,
       10836, 10969, 11085, 11187, 11244, 11362, 11489, 11540, 11716,
       11771, 11901, 11993, 12125, 12235, 12253, 12321, 12466, 12515,
       12702, 12752, 12828, 12929, 13092, 13134, 13254, 13432, 13483,
       13627])

Note :- Purchase table is derived from the purchase_invoice and purchase_price

In [28]:
# To check one specific vendor detail - so selected VendorNumver = 4466 from sales table
sales = pd.read_sql("""select * from sales where VendorNo = 4466""",conn)
sales.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [29]:
sales_group_4466_vendor = sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()
sales_group_4466_vendor

       SalesDollars  SalesPrice  SalesQuantity
Brand
5215        1649.73      948.27            127
5255        2208.30     1519.83            170

In [30]:
purchases_group_4466_vendor = purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()
purchases_group_4466_vendor

                     Quantity   Dollars
Brand PurchasePrice
5215  9.41               1021   9607.61
5255  9.35               1096  10247.60

In [31]:
purchase_sales_4466_vendor = purchases_group_4466_vendor.merge(sales_group_4466_vendor,on='Brand')
purchase_sales_4466_vendor

       Quantity   Dollars  SalesDollars  SalesPrice  SalesQuantity
Brand
5215       1021   9607.61       1649.73      948.27            127
5255       1096  10247.60       2208.30     1519.83            170

In [32]:
 purchase_sales_4466_vendor['Remianing_qty'] = purchase_sales_4466_vendor['Quantity'] - purchase_sales_4466_vendor['SalesQuantity']
 purchase_sales_4466_vendor['Profit Dollars'] =purchase_sales_4466_vendor['SalesDollars'] - purchase_sales_4466_vendor['Dollars']
 purchase_sales_4466_vendor['Sale % qty'] = ((purchase_sales_4466_vendor['SalesQuantity']/purchase_sales_4466_vendor['Quantity'])*100).round(2)
 purchase_sales_4466_vendor

,Quantity,Dollars,SalesDollars,SalesPrice,SalesQuantity,Remianing_qty,Profit Dollars,Sale % qty
Brand,,,,,,,,
5215,1021,9607.61,1649.73,948.27,127,894,-7957.88,12.44
5255,1096,10247.60,2208.30,1519.83,170,926,-8039.30,15.51

### Observation Points
* The purchases table contains acual purchase data, including the date of purchase, products (brands) purchased by vendors, the amount paid and the quantity purchased.
* The purchase price column is derived from the purchase_price table, which provides product-wise actual and purchases price
* The vendor_invoice table aggregates data from the purchase table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.
* The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold the selling price and the revenue earned

#### As the data we need for analysis in distributed tables, we need to create a summary table containing:
* Purchase transaction made by vendors
* Sales transaction data
* Freight costs for each vendor
* Actual product prices from vendors

In [40]:
freight_summary = pd.read_sql("""select VendorNumber,SUM(Freight) as FreightCost
from vendor_invoice
group by VendorNumber""",conn)
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [7]:
pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Price AS ActualPrice,
    pp.Volume,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Price,
    pp.Volume
ORDER BY TotalDollars
""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,0.99,50,1,0.71
1,9165,ULTRA BEVERAGE COMPANY LLP,9191,0.73,0.99,50,3,2.19
2,9815,WINE GROUP INC,22407,2.25,3.29,750,1,2.25
3,3960,DIAGEO NORTH AMERICA INC,8729,0.74,0.99,50,4,2.96
4,17035,PERNOD RICARD USA,8063,1.59,1.99,50,2,3.18
...,...,...,...,...,...,...,...,...
7148,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750,20653,478943.07
7149,17035,PERNOD RICARD USA,8068,18.24,24.99,1750,27600,503424.00
7150,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750,28326,620056.14
7151,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750,28772,755840.44
7152,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750,52747,852918.99

In [15]:
## Query to clean the above issue
pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Price AS ActualPrice,
    pp.Volume,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
WHERE p.PurchasePrice > 0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Price,
    pp.Volume
ORDER BY TotalDollars
""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,0.99,50,1,0.71
1,9165,ULTRA BEVERAGE COMPANY LLP,9191,0.73,0.99,50,3,2.19
2,9815,WINE GROUP INC,22407,2.25,3.29,750,1,2.25
3,3960,DIAGEO NORTH AMERICA INC,8729,0.74,0.99,50,4,2.96
4,17035,PERNOD RICARD USA,8063,1.59,1.99,50,2,3.18
...,...,...,...,...,...,...,...,...
7148,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750,20653,478943.07
7149,17035,PERNOD RICARD USA,8068,18.24,24.99,1750,27600,503424.00
7150,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750,28326,620056.14
7151,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750,28772,755840.44
7152,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750,52747,852918.99

In [14]:
pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY
    VendorNo,
    Brand
    order by TotalSalesDollars""",conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.49,0.49,1,0.05
1,3960,3303,0.99,0.99,1,0.05
2,3960,8729,0.99,0.99,1,0.05
3,7245,3096,0.99,0.99,1,0.05
4,9625,8872,0.99,0.99,1,0.05
...,...,...,...,...,...,...
6395,4425,3405,106254.57,23662.11,3543,6509.61
6396,17035,8068,117084.76,22231.41,4524,8311.97
6397,1128,1233,138165.61,29727.74,3839,7053.50
6398,3960,3545,148816.57,24501.88,4943,9082.28
6399,3960,4261,183154.71,21132.39,8329,15303.88

In [26]:
# The above combined query was showing error so we need to optimize the query
vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary AS(
select VendorNumber,SUM(Freight) as FreightCost
from vendor_invoice
group by VendorNumber),

PurchaseSummary AS(
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price as ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
        FROM purchases p
        JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY p.VendorNumber,p.VendorName,p.Brand),

SalesSummary As(
    SELECT
        VendorNo,
        Brand,
        SUM(SalesDollars) as TotalSalesDollars,
        SUM(SalesPrice) as TotalSalesPrice,
        SUM(SalesQuantity) as TotalSalesQuantity,
        SUM(ExciseTax) as TotalExciseTax
    FROM sales
    GROUP BY VendorNo,Brand)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalSalesQuantity,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNUmber
ORDER BY TotalPurchaseDollars DESC
""",conn)

In [28]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,52747,852918.99,183154.71,21132.39,8329.0,15303.88,257032.07
1,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,28772,755840.44,138165.61,29727.74,3839.0,7053.50,68601.68
2,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,28326,620056.14,148816.57,24501.88,4943.0,9082.28,257032.07
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,27600,503424.00,117084.76,22231.41,4524.0,8311.97,123780.22
4,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,20653,478943.07,106254.57,23662.11,3543.0,6509.61,144929.24

This query generates a vendor-wise sales and purchase summary,which is valuable for

##### Performance Optimization

* The query involves heavy joins and aggregations on large datasets like sales and purchases
* Storing the pre-aggregated results avoids repeated expensive computations
* Helps in analyzing sales,purchases and pricing for different vendorsand brands
* Future Benefits of storing this data for faster Dashboarding & Reporting
* Instead of running expensive queries each time,dashboards can fetch data quickly from vendor_sales_summary

In [27]:
vendor_sales_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 7153 entries, 0 to 7152
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           7153 non-null   int64
 1   VendorName             7153 non-null   str
 2   Brand                  7153 non-null   int64
 3   Description            7153 non-null   str
 4   PurchasePrice          7153 non-null   float64
 5   ActualPrice            7153 non-null   float64
 6   Volume                 7153 non-null   str
 7   TotalPurchaseQuantity  7153 non-null   int64
 8   TotalPurchaseDollars   7153 non-null   float64
 9   TotalSalesDollars      5762 non-null   float64
 10  TotalSalesPrice        5762 non-null   float64
 11  TotalSalesQuantity     5762 non-null   float64
 12  TotalExciseTax         5762 non-null   float64
 13  FreightCost            7153 non-null   float64
dtypes: float64(8), int64(3), str(3)
memory usage: 782.5 KB

In [29]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [30]:
vendor_sales_summary.isnull().sum()

VendorNumber                0
VendorName                  0
Brand                       0
Description                 0
PurchasePrice               0
ActualPrice                 0
Volume                      0
TotalPurchaseQuantity       0
TotalPurchaseDollars        0
TotalSalesDollars        1391
TotalSalesPrice          1391
TotalSalesQuantity       1391
TotalExciseTax           1391
FreightCost                 0
dtype: int64

In [33]:
vendor_sales_summary.fillna(0,inplace=True)
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesDollars        0
TotalSalesPrice          0
TotalSalesQuantity       0
TotalExciseTax           0
FreightCost              0
dtype: int64

In [34]:
vendor_sales_summary['VendorName'].unique()

<StringArray>
[            'DIAGEO NORTH AMERICA INC   ',
             'BROWN-FORMAN CORP          ',
             'PERNOD RICARD USA          ',
                   'MARTIGNETTI COMPANIES',
             'BACARDI USA INC            ',
             'PROXIMO SPIRITS INC.       ',
             'JIM BEAM BRANDS COMPANY    ',
             'ULTRA BEVERAGE COMPANY LLP ',
             'SAZERAC CO INC             ',
             'CAMPARI AMERICA            ',
 ...
             'MILTONS DISTRIBUTING CO    ',
             'BLACK ROCK SPIRITS LLC     ',
             'BRONCO WINE COMPANY        ',
             'PARK STREET IMPORTS LLC    ',
             'MANGO BOTTLING INC         ',
             'APPOLO VINEYARDS LLC       ',
 'IRA GOLDMAN AND WILLIAMS, LLP          ',
             'SILVER MOUNTAIN CIDERS     ',
             'CAPSTONE INTERNATIONAL     ',
                         'UNCORKED       ']
Length: 116, dtype: str

In [36]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()
vendor_sales_summary['VendorName'].unique()

<StringArray>
[     'DIAGEO NORTH AMERICA INC',             'BROWN-FORMAN CORP',
             'PERNOD RICARD USA',         'MARTIGNETTI COMPANIES',
               'BACARDI USA INC',          'PROXIMO SPIRITS INC.',
       'JIM BEAM BRANDS COMPANY',    'ULTRA BEVERAGE COMPANY LLP',
                'SAZERAC CO INC',               'CAMPARI AMERICA',
 ...
       'MILTONS DISTRIBUTING CO',        'BLACK ROCK SPIRITS LLC',
           'BRONCO WINE COMPANY',       'PARK STREET IMPORTS LLC',
            'MANGO BOTTLING INC',          'APPOLO VINEYARDS LLC',
 'IRA GOLDMAN AND WILLIAMS, LLP',        'SILVER MOUNTAIN CIDERS',
        'CAPSTONE INTERNATIONAL',                      'UNCORKED']
Length: 115, dtype: str

In [37]:
vendor_sales_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 7153 entries, 0 to 7152
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           7153 non-null   int64
 1   VendorName             7153 non-null   str
 2   Brand                  7153 non-null   int64
 3   Description            7153 non-null   str
 4   PurchasePrice          7153 non-null   float64
 5   ActualPrice            7153 non-null   float64
 6   Volume                 7153 non-null   float64
 7   TotalPurchaseQuantity  7153 non-null   int64
 8   TotalPurchaseDollars   7153 non-null   float64
 9   TotalSalesDollars      7153 non-null   float64
 10  TotalSalesPrice        7153 non-null   float64
 11  TotalSalesQuantity     7153 non-null   float64
 12  TotalExciseTax         7153 non-null   float64
 13  FreightCost            7153 non-null   float64
dtypes: float64(9), int64(3), str(2)
memory usage: 782.5 KB

In [39]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [40]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100

In [41]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [38]:
vendor_sales_summary['SalestoPurchaseRatio']  = vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [43]:
cursor = conn.cursor()

In [44]:
cursor.execute("""CREATE TABLE vendor_sales_summary(
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    Volume,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalestoPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber,Brand)
    );
""")

In [45]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalestoPurchaseRatio]
Index: []

In [46]:
vendor_sales_summary.to_sql('vendor_sales_summary',conn,if_exists = 'replace',index = True)

7153

In [47]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,SalestoPurchaseRatio,GrossProfit,ProfitMargin,StockTurnover
0,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,52747,852918.99,183154.71,21132.39,8329.0,15303.88,257032.07,0.214739,-669764.28,-365.682258,0.157905
1,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,28772,755840.44,138165.61,29727.74,3839.0,7053.50,68601.68,0.182797,-617674.83,-447.053959,0.133428
2,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,28326,620056.14,148816.57,24501.88,4943.0,9082.28,257032.07,0.240005,-471239.57,-316.657997,0.174504
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,27600,503424.00,117084.76,22231.41,4524.0,8311.97,123780.22,0.232577,-386339.24,-329.965437,0.163913
4,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,20653,478943.07,106254.57,23662.11,3543.0,6509.61,144929.24,0.221852,-372688.50,-350.750561,0.171549